[build]
  command = "esbuild server.js --bundle --platform=node --outdir=public"
  publish = "./public"
  timeout = 3600

[dev]
  command = "node server.js"
  port = 5500

[functions]
  node_bundler = "esbuild"

[site]
  id = "digvijaygour07"

[deploy]
  target = "production"
