[build]
  command = "npx rollup -c rollup.config.mjs"
  publish = "public"
  environment = { NODE_VERSION = "18.20.4" }

[dev]
  command = "npm run dev"
  port = 5500
  environment = { NODE_ENV = "development" }

[functions]
  directory = ".netlify/functions"

[functions.path]
  "/api/my-function" = "myFunction.js"

[site]
  id = "086500c0-77bb-427e-8aa1-d3d74374a9ac"
  name = "kuwarpay"

[deploy]
  target = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[context]
  [context.production]
    environment = { NODE_ENV = "production" }

  [context.development]
    environment = { NODE_ENV = "development" }

[[files]]
  include = "**/*"
  exclude = "node_modules/*"

[scripts]
  build = "rollup -c rollup.config.mjs"
  dev = "rollup -c rollup.config.mjs --watch"